config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/new'
  get 'users/edit'
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  resources :users, except: [:new]
  get 'signup', to:'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5 }
  validates :user_id, presence: true
  belongs_to :user
  delegate :username, to: :user, allow_nil: true
  has_many :article_categories
  has_many :categories, through: :article_categories

  def self.search(search)
    where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%") 
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
            length: { minimum: 5, maximum: 25 }
  has_many :article_categories
  has_many :articles, through: :article_categories
  # delegate :title, to: :article, allow_nil: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email = self.email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
              length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX  }
  has_many :articles, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You need to be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created!"
      redirect_to categories_path
    else
      flash[:info] = "Category was not created!"
      render 'new'
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category was updated!"
      redirect_to category_path(@category)
    else
      flash[:info] = "Category was not updated!"
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = "Removed this category and all its articles!"
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin? )
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in successfully!"
      redirect_to user_path(user)
    else
      flash[:danger] = "Failed login!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logout successfully!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :require_exact_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Hello #{@user.username} - Welcome to my blog!"
      redirect_to user_path(@user)
    else
      flash[:info] = "Failed Sign Up!"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Updated User!"
      redirect_to articles_path
    else
      flash[:info] = "Failed Update!"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been removed! "
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :admin)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_exact_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit your accout"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin user can perform that action"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
  <div class="listing">
  <% obj.each do |article| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="detail-article">
        <h2>
          <%= link_to article.title, article_path(article) %>
        </h2>
        <%= gravatar_for(article.user, size: 30) %>
        <span class="more-info">Created by: <%= article.username %> | <%= time_ago_in_words(article.created_at) %> ago</span>
        <p><%= truncate sanitize(article.description, tags: [], attributes: [], length: 150) %></p>
        <% if params[:controller] != "categories" %>
          <% if article.categories.any? %>
              <p>Categories: <%= render article.categories %></p>
            <% end %>
          <% end %>
        <% if logged_in? && ( current_user == article.user || current_user.admin? ) %>
          <p><%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary" %>
          <%= link_to 'Remove', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></p>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'layouts/error_messages', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.cktext_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="clearfix"></div>

app/views/articles/edit.html.erb
<h2 align="center">Edit article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<% if @articles.blank? %>
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <h5 style="color: #ef5350;">There are no recipes containing the term <%= params[:search] %></h5>
    </div>
  </div>
<% else %>
  <h2 class="text-center">All Article</h2>
  <div align="center">
    <%= will_paginate %>
  </div>
  <%= render 'article', obj: @articles %>

  <div align="center">
    <%= will_paginate %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h2 align="center">Create a new article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center">Detail Article</h2>
<div class="listing">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="detail-article fit-content">
        <h2><%= @article.title %></h2>
        <%= gravatar_for(@article.user, size: 30) %>
        <span class="more-info">
          Created by: <%= @article.username %> | <%= time_ago_in_words(@article.created_at) %> ago
        </span>

        <% if @article.categories.any? %>
            <p>Categories: <%= render @article.categories %></p>
            <p><%= sanitize(@article.description) %></p>
          <% end %>
        <% if logged_in? && ( current_user == @article.user || current_user.admin? ) %>
          <p>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary" %>
            <%= link_to 'Remove', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render 'layouts/error_messages', obj: @category %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control", placeholder: "name of category" %>
  </div>

  <div><%= f.submit class:"btn btn-primary" %></div>
<% end %>

app/views/categories/index.html.erb
<div class="text-center">
  <h2>All Categories</h2>
</div>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing-user">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to category.name, category_path(category) %></li>
          <li>
            <p><small><%= pluralize(category.articles.count, "article") %></small></p>
          </li>
          <% if logged_in? &&  current_user.admin? %>
            <li><%= link_to 'Edit', edit_category_path(category), class:"btn btn-primary" %></li>
            <li><%= link_to 'Remove', category_path(category), method: :delete, data: { confirm: "Are you sure remove this category and all its articles!" }, class: "btn btn-danger" %>
            </li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h2 class="text-center">New Category</h2>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h2 class="text-center"><%= "All  " + @category.name + "'s Articles" %></h2>

<div align="center">
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading panel-heading-error">
          <h3 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h3>

          <div class="panel-body">

            <ul>

              <% obj.errors.full_messages.each do |msg| %>

                <li><%= msg %></li>

              <% end %>

            </ul>

          </div>

        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Viet's Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= render 'layouts/flash_messages' %>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container about">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading panel-about">
          <span class="title">About Me</span>
        </div>

        <ul class="list-group" id="contact-list">
          <li class="list-group-item">
            <div class="col-xs-12 col-sm-3">
              <%= image_tag("ltviet.jpg", alt: "Le Thanh Viet", class: "img-responsive img-circle") %>
            </div>
            <div class="col-xs-12 col-sm-9">
              <span class="name">Le Thanh Viet</span><br/>
              <p><em>I like coffee, football, travel, and technology :) </em></p>
              <span class="glyphicon glyphicon-map-marker text-muted c-info" data-toggle="tooltip" title="District 12, Ho Chi Minh City"></span>
              <span class="visible-xs"> <span class="text-muted">District 12, Ho Chi Minh City</span><br/></span>
              <span class="glyphicon glyphicon-earphone text-muted c-info" data-toggle="tooltip" title="(097) 242-6820"></span>
              <span class="visible-xs"> <span class="text-muted">(097) 242-6820</span><br/></span>
              <span class="fa fa-comments text-muted c-info" data-toggle="tooltip" title="vietleuit@gmail.com"></span>
              <span class="visible-xs"> <span class="text-muted">vietleuit@gmail.com</span><br/></span>
            </div>
            <div class="clearfix"></div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading panel-about">
          <span class="title">About Me</span>
        </div>

        <ul class="list-group" id="contact-list">
          <li class="list-group-item">
            <div class="col-xs-12 col-sm-3">
              <%= image_tag("ltviet.jpg", alt: "Le Thanh Viet", class: "img-responsive img-circle") %>
            </div>
            <div class="col-xs-12 col-sm-9">
              <span class="name">Le Thanh Viet</span><br/>
              <p><em>I like coffee, football, travel, and technology :) </em></p>
              <span class="glyphicon glyphicon-map-marker text-muted c-info" data-toggle="tooltip" title="District 12, Ho Chi Minh City"></span>
              <span class="visible-xs"> <span class="text-muted">District 12, Ho Chi Minh City</span><br/></span>
              <span class="glyphicon glyphicon-earphone text-muted c-info" data-toggle="tooltip" title="(097) 242-6820"></span>
              <span class="visible-xs"> <span class="text-muted">(097) 242-6820</span><br/></span>
              <span class="fa fa-comments text-muted c-info" data-toggle="tooltip" title="vietleuit@gmail.com"></span>
              <span class="visible-xs"> <span class="text-muted">vietleuit@gmail.com</span><br/></span>
            </div>
            <div class="clearfix"></div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <!-- <div class="container"> -->
    <h2>Hello, World!</h2>
    <p>My fullname is: Le Thanh Viet. This is my personal blog </p>
    <p>I store everything during my self-study on this blog</p>
    <p>If you interesting, come and share your knowledge <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></p>
  <!-- </div> -->
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>Viet's Blog &copy; 2019</p>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png', id: 'logo'), root_path, class:"navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Articles', articles_path %> <span class="sr-only">(current)</span></li>
        <li><%= link_to 'Authors', users_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-togglex" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Categories', categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
            </ul>
          </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-togglex" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">New <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Article', new_article_path %></li>
              <% if current_user.admin? %>
                <li><%= link_to 'Category', new_category_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <%= form_tag(articles_path, method: :get, id: "search-form", class: "navbar-form navbar-left") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Article", class: "form-control" %>
        <%= submit_tag "Search", name:nil, class: "btn btn-primary" %>
    <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <%= " - Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Account', edit_user_path(current_user) %></li>
              <li><%= link_to 'View Account', user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading text-center">Category</div>

  <!-- List group -->
  <ul class="list-group text-center">
    <li class="list-group-item">Front-End</li>
    <li class="list-group-item">Back-End</li>
    <li class="list-group-item">Courses</li>
    <li class="list-group-item">Notes</li>
    <li class="list-group-item">Tricks</li>
  </ul>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'layouts/error_messages', obj: @user %>
  <div class="form-group">
    <%= f.text_field :username, class:"form-control", placeholder: "username" %>
  </div>

  <div class="form-group">
    <%= f.email_field :email, class:"form-control", placeholder:"email" %>
  </div>

  <div class="form-group">
    <%= f.password_field :password, class:"form-control", placeholder:"password" %>
  </div>

  <div>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 class="text-center">Edit Your Account</h2>

<div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="text-center">
  <h2>Authors</h2>
  <h5>Thank you to everyone who has contributed knowledge to Viet's Blog <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></h5>
</div>

<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing-user">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          <% if logged_in? && current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2 class="text-center">Sign Up for Viet's Blog</h2>

<div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="listing">
  <div class="text-center">
    <h3><%= @user.username %>'s Articles</h3>
    <%= gravatar_for @user %>
  </div>

  <div class="row">
    <% if @user_articles.any? %>
      <div align="center">
        <%= will_paginate @user_articles %>
      </div>
      <%= render 'articles/article', obj: @user_articles %>
      <div align="center">
        <%= will_paginate @user_articles %>
      </div>
    <% else %>
      <div class="col-md-8 col-md-offset-2">
        <div class="well">
          <h5 style="color: #ef5350;", class="text-center">NO ARTICLE</h5>
        </div>
      </div>
    <% end %>
  </div>
</div>